<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class ProductStockHistory extends Model
{
    protected $appends = ['stock_quantity'];

    public function getStockQuantityAttribute()
    {
        $debit = $this->purchase_qty + $this->req_received;
        $credit = $this->sell_qty + $this->req_send;
        $total = $debit - $credit;

        return $total;
    }

    public function branch(){
        return $this->belongsTo(Branch::class)->withTrashed();
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('branch', function (Builder $builder) {
            $builder->where('business_id', '=', Auth::user()->business_id);
        });
    }
}
